ALTER SESSION SET CONTAINER = TESTE;
ALTER SESSION SET CURRENT_SCHEMA = ESTOQUE_TESTE;
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE services (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(150) NOT NULL,
    description VARCHAR2(500),
    status VARCHAR2(30) DEFAULT 'pending',
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_services_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

INSERT INTO users (name, email, password)
VALUES ('Usuário Teste', 'teste@email.com', '123456');

INSERT INTO services (title, description, status, user_id)
VALUES ('Serviço de teste', 'Solicitação criada no banco de desenvolvimento', 'pending', 1);

COMMIT;






-- -------------------------------------------
-- Tabela de produtos para teste de estoque
-- -------------------------------------------

CREATE TABLE PRODUTO (
    CD_PRODUTO NUMBER PRIMARY KEY,
    DS_PRODUTO VARCHAR2(150) NOT NULL,
    CD_ESPECIE NUMBER DEFAULT 10
);

CREATE TABLE EST_PRO (
    CD_PRODUTO NUMBER,
    CD_ESTOQUE NUMBER DEFAULT 1,
    QT_ESTOQUE_ATUAL NUMBER DEFAULT 0,
    CONSTRAINT fk_est_pro_produto FOREIGN KEY (CD_PRODUTO) REFERENCES PRODUTO(CD_PRODUTO)
);

-- Os IDs precisam fazer sentido com a logica de codigo de barras em utils/barcode.py (id_to_barcode)
-- Se CD_PRODUTO = 1, o codigo gerado e aceito sera '1000000001'
INSERT INTO PRODUTO (CD_PRODUTO, DS_PRODUTO, CD_ESPECIE) VALUES (1, 'Dipirona 500g', 10);
INSERT INTO EST_PRO (CD_PRODUTO, CD_ESTOQUE, QT_ESTOQUE_ATUAL) VALUES (1, 1, 200);

INSERT INTO PRODUTO (CD_PRODUTO, DS_PRODUTO, CD_ESPECIE) VALUES (2, 'Paracetamol 750mg', 10);
INSERT INTO EST_PRO (CD_PRODUTO, CD_ESTOQUE, QT_ESTOQUE_ATUAL) VALUES (2, 1, 150);

INSERT INTO PRODUTO (CD_PRODUTO, DS_PRODUTO, CD_ESPECIE) VALUES (3, 'Amoxicilina 500mg', 10);
INSERT INTO EST_PRO (CD_PRODUTO, CD_ESTOQUE, QT_ESTOQUE_ATUAL) VALUES (3, 1, 80);

COMMIT;