name: RTP Patrimonio Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-local:
    runs-on: self-hosted
    if: github.ref_type == 'tag' && (github.event.base_ref == 'refs/heads/develop' || contains(github.ref, 'develop'))
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Preparar ambiente
        run: echo "ambiente preparado no servidor SRVPROJETO"
            
      - name: Criar arquivo .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "Arquivo .env gerado com sucesso!"
          
      - name: Build e Deploy com Docker
        run: |
          docker compose down
          docker compose up --build -d
          echo "Deploy finalizado com sucesso!"